name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Simulate World
      id: simulate-world
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Simulate World
        setup-command: ''
        command: python world.py
        input: cutie
        expected-output: pie
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SIMULATE-WORLD_RESULTS: "${{steps.simulate-world.outputs.result}}"
      with:
        runners: simulate-world
